branch-defaults:
  master:
    environment: Test-env
    group_suffix: null
environment-defaults:
  Test-env:
    branch: null
    repository: null
global:
  application_name: test
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: ap-southeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
